### ISSUE TITLE
Return answer value

### ISSUE THREAD

**Issue by hamamulfz** [jvanovost/dc09_spt#1]
Hi, i am currently trying to use your module to communicate with sia server
i want to save server answer to a return variable and take it into database as log (this will done using php).
i've try to modify your module, but because the answer comes late, i can't catch the variable.
how can i achieve this with your module (get the server answer as return variable of a function) ? thanks

**Comment by jvanovost** [comment]
Hi hamamulfz,
The sending of messages is indeed, happening asynchronous from a queue.
The real transfer is done by the transfer_msg function.
The handling of the response is there and the logging of the answer too.

If you like to catch the answer it should be done in the transfer_msg function.

but ..
Maybe you would like to adapt the logging class to store the info in your database ? In that case you even have more insight in the proceedings..
